### ISSUE TITLE
Feedback for personalmovie (문승현 튜터)

### ISSUE THREAD

**Issue by bewisesh91** [Jindonglee/personalmovie#1]
안녕하세요 :) 첫 개인 과제 제출 고생하셨습니다! 아래 체크 리스트 바탕으로 피드백을 드리려고 해요!

개인 과제 기본 구현 사항 체크
[1] jQuery 라이브러리 사용없이 순수 바닐라 자바스크립트 사용하기 👍 💯
[2] TMDB 오픈 API를 이용하여 인기영화 데이터 가져오기 👍 💯
[3] 영화정보 카드 리스트 UI 구현 👍 💯
[4] 영화 검색 UI 구현 👍 💯
[5] 하기 기재된 Javascript 문법 요소를 이용하여 구현 👍 💯

기본 구현 사항 모두 잘 반영하신 것 같습니다.
이외에 피드백드리고 싶은 점을 정리해보자면 다음과 같습니다.

1. 배포
- 프로젝트를 완결성 있게 배포까지 하신 점 칭찬합니다!
- 제가 직접 깃을 클론해서 프로젝트를 실행하지 않아도 되어서 편리했습니다.
- 이렇게 사용자가 편리할 수 있도록 완결성 있게 결과물을 도출하는 것 역시 개발자로서 좋은 역량이라고 생각합니다.

2. 불필요한 주석
- 사람마다 생각이 다를 수 있지만, 개인적으로 저는 주석이 없는 코드가 좋은 코드라고 생각해요.
- 주석이 없어도 충분히 이해할 수 있는 코드를 작성하도록 연습을 해보면 좋을 것 같아요.
- 사실 지금도 코드를 잘 작성하셨는데 중간 중간에 불필요한 주석들이 많은 것 같습니다.
- 디버깅을 위해 넣어놓은 console.log 같은 코드들도 삭제하면 좋을 것 같아요.

3. 전반적인 UI
- 페이지 이름은 못생긴 영화검색 사이트지만 상당히 UI를 신경쓰신 것 같아요.
- 기능 구현만으로도 요구사항을 충족할 수 있었을 텐데 추가적인 노력을 쏟으신 점 멋지십니다.
- 기대 이상의 무엇인 가를 해내는 것 역시 개발자의 좋은 역량인 것 같아요.

**Comment by Jindonglee** [comment]
피드백 정말 감사드립니다.
주석은 팀원들과 코드리뷰할때 쓰려고 쓴건데 미처 지우질 못했네요...ㅠㅠ
상세한 피드백 다시한번 감사드립니다!!




2024년 1월 8일 (월) 오후 10:54, Seunghyun Mun ***@***.***>님이 작성:
